# Generated by Django 5.2.17 on 2026-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('INSTRUCTOR', 'Instructor')], default='SUPER_ADMIN', max_length=20),
        ),
    ]
