# Generated by Django 5.2.17 on 2026-08-05 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=10)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('relationship', models.CharField(default='Father', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('instructor', models.CharField(default='Sensei Abdul Rahman', max_length=255)),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('current_belt', models.CharField(default='White Belt', max_length=50)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended')], default='Active', max_length=20)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='branches.branch')),
            ],
        ),
    ]
