# Generated by Django 5.2.17 on 2026-08-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default='Pulikkal, Malappuram, Kerala', null=True),
        ),
    ]
