# Generated by Django 5.2.17 on 2026-08-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
