# Generated by Django 5.2.17 on 2026-08-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_fee_status_student_initial_paid_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('Morning Batch (6:00 AM - 7:30 AM)', 'Morning Batch (6:00 AM - 7:30 AM)'), ('Evening Batch (5:00 PM - 7:00 PM)', 'Evening Batch (5:00 PM - 7:00 PM)'), ('Weekend Special Batch (Sat & Sun: 7:00 AM - 9:00 AM)', 'Weekend Special Batch (Sat & Sun: 7:00 AM - 9:00 AM)')], default='Evening Batch (5:00 PM - 7:00 PM)', max_length=100),
        ),
    ]
