# Generated by Django 5.2.17 on 2026-08-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(choices=[('Evening Batch (5:00 PM - 7:00 PM)', 'Evening Batch (5:00 PM - 7:00 PM)'), ('Morning Batch (6:00 AM - 7:30 AM)', 'Morning Batch (6:00 AM - 7:30 AM)'), ('Night / Late Evening Batch (7:00 PM - 8:30 PM)', 'Night / Late Evening Batch (7:00 PM - 8:30 PM)'), ('Weekend Special Batch (Sat & Sun: 7:00 AM - 9:00 AM)', 'Weekend Special Batch (Sat & Sun: 7:00 AM - 9:00 AM)'), ('Ladies Special Batch', 'Ladies Special Batch'), ('Kids Special Batch (4:00 PM - 5:00 PM)', 'Kids Special Batch (4:00 PM - 5:00 PM)'), ('Custom Shift / Flexible', 'Custom Shift / Flexible')], default='Evening Batch (5:00 PM - 7:00 PM)', max_length=100),
        ),
    ]
