# Generated by Django 5.2.11 on 2026-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='shift',
            field=models.CharField(blank=True, default='Evening Batch (5:00 PM - 7:00 PM)', max_length=255, null=True),
        ),
    ]
