# Generated by Django 5.2.11 on 2026-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_student_admission_no_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, default='Parent', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='initial_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=500.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='+91 9544085442', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='whatsapp',
            field=models.CharField(blank=True, default='+91 9544085442', max_length=30, null=True),
        ),
    ]
