# Generated by Django 5.2.17 on 2026-08-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_student_blood_group_alter_student_fee_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_fee_paid',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_fee_paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_frequency',
            field=models.CharField(blank=True, default='MONTHLY', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='paid_months',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fee_status',
            field=models.CharField(blank=True, default='Paid', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='pending_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
