# Generated by Django 5.2.11 on 2026-09-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_admission_fee_student_admission_fee_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(blank=True, default='Karate (Shotokan)', max_length=150, null=True),
        ),
    ]
