# Generated by Django 5.2.17 on 2026-08-05 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
