# Generated by Django 5.2.17 on 2026-08-05 06:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeltGrading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_belt', models.CharField(max_length=50)),
                ('target_belt', models.CharField(max_length=50)),
                ('exam_date', models.DateField()),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Pass', max_length=20)),
                ('examiner', models.CharField(default='Sensei Abdul Rahman (5th Dan)', max_length=255)),
                ('certificate_no', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('next_eligible_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_history', to='students.student')),
            ],
        ),
    ]
