# Generated by Django 5.2.17 on 2026-08-17 04:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_grading', '0001_initial'),
        ('students', '0006_alter_student_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=50, unique=True)),
                ('form_type', models.CharField(choices=[('JKK_KERALA', 'JKK Kerala Kyu Registration (White to Brown-4)'), ('JKA_JAPAN', 'JKA Japan Senior Kyu & Dan Registration (Brown-3 to Black Belt)')], default='JKK_KERALA', max_length=30)),
                ('admission_no', models.CharField(blank=True, max_length=50, null=True)),
                ('student_name', models.CharField(max_length=255)),
                ('photo', models.TextField(blank=True, null=True)),
                ('photo_secondary', models.TextField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=10)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('height_cm', models.DecimalField(decimal_places=1, default=140.0, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=35.0, max_digits=5)),
                ('branch_name', models.CharField(default='Pulikkal Dojo', max_length=255)),
                ('school_or_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('class_or_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_relationship', models.CharField(default='Father', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('current_belt', models.CharField(default='White Belt', max_length=50)),
                ('current_kyu', models.CharField(default='10th Kyu', max_length=20)),
                ('target_belt', models.CharField(default='Yellow Belt', max_length=50)),
                ('target_kyu_or_dan', models.CharField(default='9th Kyu', max_length=20)),
                ('belt_size', models.CharField(default='Size 3 (160 cm)', max_length=50)),
                ('training_period_years', models.CharField(default='1 Year 0 Months', max_length=50)),
                ('jka_member_no', models.CharField(blank=True, max_length=100, null=True)),
                ('jka_nationality', models.CharField(default='INDIAN', max_length=50)),
                ('jka_organization', models.CharField(default='JKA INDIA', max_length=100)),
                ('instructor_reference_name', models.CharField(default='Sensei Abdul Rahman', max_length=255)),
                ('instructor_reference_address', models.TextField(blank=True, default='Pulikkal, Malappuram', null=True)),
                ('instructor_reference_phone', models.CharField(default='9961576993', max_length=20)),
                ('dan_kyu_certificate_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_last_conferral', models.DateField(blank=True, null=True)),
                ('instructor_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('examiner_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('judge_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('UPI / GPay / PhonePe', 'UPI / GPay / PhonePe'), ('Cash at Dojo / Club', 'Cash at Dojo / Club')], default='UPI / GPay / PhonePe', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid / Verified', 'Paid / Verified'), ('Refunded', 'Refunded')], default='Pending', max_length=30)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('exam_status', models.CharField(choices=[('Registered', 'Registered'), ('Approved', 'Approved'), ('Passed', 'Passed'), ('Probation', 'Probation'), ('Failed', 'Failed'), ('Absent', 'Absent')], default='Registered', max_length=30)),
                ('kihon_score', models.CharField(blank=True, max_length=20, null=True)),
                ('kata_score', models.CharField(blank=True, max_length=20, null=True)),
                ('kumite_score', models.CharField(blank=True, max_length=20, null=True)),
                ('adaptation_score', models.CharField(blank=True, max_length=20, null=True)),
                ('examiner_remarks', models.TextField(blank=True, null=True)),
                ('examiner_signature', models.CharField(default='Sensei Abdul Rahman (5th Dan)', max_length=255)),
                ('qr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registrations', to='students.student')),
            ],
        ),
    ]
