# Generated by Django 5.2.17 on 2026-08-17 07:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_grading', '0002_gradingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_code', models.CharField(max_length=50, unique=True)),
                ('exam_date', models.DateField()),
                ('registration_start', models.DateField(blank=True, null=True)),
                ('registration_end', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(default='Main Dojo, Pulikkal', max_length=255)),
                ('exam_fee', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('eligible_belt', models.CharField(default='All Belts', max_length=100)),
                ('target_belt', models.CharField(blank=True, max_length=100, null=True)),
                ('max_candidates', models.IntegerField(default=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Closed', 'Closed'), ('Completed', 'Completed')], default='Active', max_length=20)),
                ('payment_required', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-exam_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='applied_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='current_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='date_of_confirmation',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='employer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='form_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='nationality',
            field=models.CharField(default='INDIAN', max_length=50),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='organization',
            field=models.CharField(default='JKK / JKA', max_length=100),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='present_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='registration_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Payment', 'Pending Payment'), ('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Exam Completed', 'Exam Completed'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Probation', 'Probation'), ('Absent', 'Absent'), ('Result Published', 'Result Published')], default='Submitted', max_length=30),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='years_months_training',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='exam_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Pending Payment', 'Pending Payment'), ('Registered', 'Registered'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Exam Completed', 'Exam Completed'), ('Passed', 'Passed'), ('Failed', 'Failed'), ('Probation', 'Probation'), ('Absent', 'Absent'), ('Result Published', 'Result Published')], default='Submitted', max_length=30),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='form_type',
            field=models.CharField(choices=[('JKK_WHITE_TO_BROWN_4', 'JKK White to Brown-4 Application Form'), ('JKK_BROWN', 'JKK Brown Kyu Registration Form (Brown-3 to Brown-1)'), ('JAPAN_DIRECT_BLACK_BELT', 'Japan Direct Black Belt Examination Form'), ('JKK_KERALA', 'JKK Kerala Kyu Registration (White to Brown-4)'), ('JKA_JAPAN', 'JKA Japan Senior Kyu & Dan Registration')], default='JKK_WHITE_TO_BROWN_4', max_length=50),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid / Verified', 'Paid / Verified'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='gradingregistration',
            name='exam_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='belt_grading.examschedule'),
        ),
    ]
