# Generated by Django 5.2.11 on 2026-08-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_grading', '0003_examschedule_gradingregistration_applied_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingregistration',
            name='age',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='applied_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='belt_size',
            field=models.CharField(blank=True, default='Size 3 (160 cm)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='branch_name',
            field=models.CharField(blank=True, default='Pulikkal Dojo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='current_belt',
            field=models.CharField(blank=True, default='White Belt', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='current_kyu',
            field=models.CharField(blank=True, default='10th Kyu', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='exam_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=1000.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='exam_status',
            field=models.CharField(blank=True, default='Submitted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='examiner_signature',
            field=models.CharField(blank=True, default='Sensei Abdul Rahman (5th Dan)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='guardian_name',
            field=models.CharField(blank=True, default='Parent/Guardian', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='guardian_relationship',
            field=models.CharField(blank=True, default='Father', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, default=140.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='instructor_reference_name',
            field=models.CharField(blank=True, default='Sensei Abdul Rahman', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='instructor_reference_phone',
            field=models.CharField(blank=True, default='+91 95440 85442', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='jka_nationality',
            field=models.CharField(blank=True, default='INDIAN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='jka_organization',
            field=models.CharField(blank=True, default='JKA INDIA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='nationality',
            field=models.CharField(blank=True, default='INDIAN', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='organization',
            field=models.CharField(blank=True, default='JKK / JKA', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='payment_mode',
            field=models.CharField(blank=True, default='UPI / GPay / PhonePe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='payment_status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='registration_status',
            field=models.CharField(blank=True, default='Submitted', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='target_belt',
            field=models.CharField(blank=True, default='Yellow Belt', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='target_kyu_or_dan',
            field=models.CharField(blank=True, default='9th Kyu', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='training_period_years',
            field=models.CharField(blank=True, default='1 Year 0 Months', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gradingregistration',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, default=35.0, max_digits=5, null=True),
        ),
    ]
