# Generated by Django 5.2.17 on 2026-08-05 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch_head', models.CharField(max_length=255)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('is_head_office', models.BooleanField(default=False)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('timings', models.CharField(default='Mon-Sat: 6 AM - 7 PM', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
    ]
