# Generated by Django 5.2.11 on 2026-08-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='admission_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Branch-specific admission fee override', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Branch-specific monthly fee override', max_digits=10, null=True),
        ),
    ]
