# Generated by Django 5.2.17 on 2026-08-17 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_admission_fee', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('default_monthly_fee', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('effective_month', models.CharField(default='August 2026', max_length=50)),
                ('apply_to_existing_cadets', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeRateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('MONTHLY', 'Monthly Cadet Fee'), ('ADMISSION', 'One-Time Admission Fee')], default='MONTHLY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fee rate histories',
                'ordering': ['-effective_from', '-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
